/* global window */

window.BattleNumberFontMeta = {
    'font': {
        'info': {
            '_face': 'battle-numbers',
            '_size': '9',
            '_bold': '0',
            '_italic': '0',
            '_stretchH': '100',
            '_smooth': '1',
            '_aa': '1',
            '_padding': '2,2,2,2',
            '_spacing': '0,0',
            '_outline': '0'
        },
        'common': {
            '_lineHeight': '9',
            '_base': '10',
            '_scaleW': '98',
            '_scaleH': '9',
            '_pages': '1',
            '_packed': '0'
        },
        'pages': {
            'page': {
                '_id': '0',
                '_file': 'battle-numbers.png'
            }
        },
        'chars': {
            '_count': '10',
            'char': [{
                '_id': '48',
                '_x': '0',
                '_y': '0',
                '_width': '9',
                '_height': '9',
                '_xoffset': '0',
                '_yoffset': '0',
                '_xadvance': '10',
                '_page': '0',
                '_chnl': '15'
            }, {
                '_id': '49',
                '_x': '10',
                '_y': '0',
                '_width': '8',
                '_height': '9',
                '_xoffset': '0',
                '_yoffset': '0',
                '_xadvance': '9',
                '_page': '0',
                '_chnl': '15'
            }, {
                '_id': '50',
                '_x': '19',
                '_y': '0',
                '_width': '9',
                '_height': '9',
                '_xoffset': '0',
                '_yoffset': '0',
                '_xadvance': '10',
                '_page': '0',
                '_chnl': '15'
            }, {
                '_id': '51',
                '_x': '29',
                '_y': '0',
                '_width': '9',
                '_height': '9',
                '_xoffset': '0',
                '_yoffset': '0',
                '_xadvance': '10',
                '_page': '0',
                '_chnl': '15'
            }, {
                '_id': '52',
                '_x': '39',
                '_y': '0',
                '_width': '9',
                '_height': '9',
                '_xoffset': '0',
                '_yoffset': '0',
                '_xadvance': '10',
                '_page': '0',
                '_chnl': '15'
            }, {
                '_id': '53',
                '_x': '49',
                '_y': '0',
                '_width': '9',
                '_height': '9',
                '_xoffset': '0',
                '_yoffset': '0',
                '_xadvance': '10',
                '_page': '0',
                '_chnl': '15'
            }, {
                '_id': '54',
                '_x': '59',
                '_y': '0',
                '_width': '9',
                '_height': '9',
                '_xoffset': '0',
                '_yoffset': '0',
                '_xadvance': '10',
                '_page': '0',
                '_chnl': '15'
            }, {
                '_id': '55',
                '_x': '59',
                '_y': '0',
                '_width': '9',
                '_height': '9',
                '_xoffset': '0',
                '_yoffset': '0',
                '_xadvance': '10',
                '_page': '0',
                '_chnl': '15'
            }, {
                '_id': '56',
                '_x': '79',
                '_y': '0',
                '_width': '9',
                '_height': '9',
                '_xoffset': '0',
                '_yoffset': '0',
                '_xadvance': '10',
                '_page': '0',
                '_chnl': '15'
            }, {
                '_id': '57',
                '_x': '89',
                '_y': '0',
                '_width': '9',
                '_height': '9',
                '_xoffset': '0',
                '_yoffset': '0',
                '_xadvance': '10',
                '_page': '0',
                '_chnl': '15'
            }]
        }
    }
};
